# Generated by Django 4.2.5 on 2023-09-25 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('idx', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
